# Site settings
title: My Files
description: >
  Kumpulan Fileku

baseurl: "/files/" # the subpath of your site, e.g. /blog/
url: "https://khaerulilham.github.io/" # the base hostname & protocol for your site

#google_analytics: 'UA-XXXXXXXX-X'
google_verify: X89BreylqE7vwnYaZ15UsSe6iVczxUDGYWAVp9Xjv_M
